services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express_server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - server/.env.prod
    restart: unless-stopped
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: angular_client
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
