name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    client:
        name: Client (Angular) - Lint, Test, Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: client
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: client/package-lock.json

            - name: Install dependencies
              run: npm install --legacy-peer-deps

            - name: TypeScript check
              run: npm run ts-check

            - name: Lint
              run: npm run lint

            - name: Setup Chrome (for Karma Headless)
              uses: browser-actions/setup-chrome@v1

            - name: Test
              run: npm run test -- --watch=false --browsers=ChromeHeadless

            - name: Build
              run: npm run build

    server:
        name: Server (Express) - Lint, Test, Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: server/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: TypeScript check
              run: npm run ts-check

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build
